### ISSUE TITLE
[Page issue] https://flutter.cn/docs/development/platform-integration/web/wasm

### ISSUE THREAD

**Issue by liudonghua123** [cfug/flutter.cn#1294]
### 页面 URL

https://flutter.cn/docs/development/platform-integration/web/wasm

### 页面源地址

https://docs.flutter.dev/platform-integration/web/wasm

### 描述问题

部分页面无法访问，例如 [wasm](https://docs.flutter.dev/platform-integration/web/wasm) 对应的 https://flutter.cn/docs/development/platform-integration/web/wasm

### 期望如何修复

同步 https://github.com/flutter/website/blob/main/src/platform-integration/web/wasm.md

**Comment by chenglu** [comment]
经历了一个大版本发布，文档同步工作正在进行中，预计今天中午可以提交 sync 的 PR。

**Comment by chenglu** [comment]
https://docs.flutter.dev/platform-integration/web/wasm

-->

https://flutter.cn/docs/platform-integration/web/wasm

**Comment by liudonghua123** [comment]
> https://docs.flutter.dev/platform-integration/web/wasm
> 
> -->
> 
> https://flutter.cn/docs/platform-integration/web/wasm

https://docs.flutter.dev/platform-integration/web/wasm 对应的 sidenav 官方仓库里面也还没有更新，不知道为什么？

https://github.com/flutter/website/blob/249dc5c61a53289abaef99341864c15bf6a135b0/src/_data/sidenav.yml#L222-L234

这里还需要增加一项

```yml
    - title: Web
      permalink: /platform-integration/web
      children:
        - title: Building web apps
          permalink: /platform-integration/web/building
        - title: Web FAQ
          permalink: /platform-integration/web/faq
        - title: Web renderers
          permalink: /platform-integration/web/renderers
        - title: Custom app initialization
          permalink: /platform-integration/web/initialization
        - title: Displaying images on the web
          permalink: /platform-integration/web/web-images
        - title: Support for WebAssembly (Wasm)
          permalink: /platform-integration/web/wasm
```
